### ISSUE TITLE
:bug: invalid configuration schema in config.d.ts, the following definitions are not supporte

### ISSUE THREAD

**Issue by thiago-scherrer** [AntoineDao/backstage-provider-kubernetes#6]
Hello!
I'm trying to use the plugin, but I'm getting the error below:

```
Backend failed to start up Error: Invalid configuration schema in node_modules/@antoinedao/backstage-provider-kubernetes/config.d.ts, the following definitions are not supported:

  Record<string,{cluster:string;filters?:{resources?:any[]|undefined;namespace?:string|undefined;labelSelector?:string|undefined;}|undefined;processor?:{namespaceOverride?:string|undefined;lifecyle?:string|undefined;defaultOwner?:string|undefined;}|undefined;schedule?:any;}>
    at /app/node_modules/@backstage/backend-app-api/node_modules/@backstage/config-loader/dist/index.cjs.js:367:15
    at Array.map (<anonymous>)
    at compileTsSchemas (/app/node_modules/@backstage/backend-app-api/node_modules/@backstage/config-loader/dist/index.cjs.js:341:27)
    at async collectConfigSchemas (/app/node_modules/@backstage/backend-app-api/node_modules/@backstage/config-loader/dist/index.cjs.js:318:21)
    at async Object.loadConfigSchema (/app/node_modules/@backstage/backend-app-api/node_modules/@backstage/config-loader/dist/index.cjs.js:507:15)
    at async Object.createConfigSecretEnumerator (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:198:55)
    at async Object.loadBackendConfig (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:456:28)
    at async main (/app/packages/backend/dist/index.cjs.js:236:18)

```

- app-config.yaml
```
catalog:
  providers:
    kubernetes:
      42-production:
        cluster: 42
        processor:
          namespaceOverride: default
          defaultOwner: guests
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 1
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
...

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: https://42.42.42.42
          name: 42
          authProvider: "google"
          skipTLSVerify: true
          skipMetricsLookup: false
          dashboardApp: gke
          dashboardParameters:
            projectId: 4242
            region: 42
            clusterName: 42
```

- yarn backstage-cli info
```
$ /app/node_modules/.bin/backstage-cli info
OS:   Linux 5.15.146+ - linux/x64
node: v18.20.1
yarn: 1.22.19
cli:  0.25.2 (installed)
backstage:  N/A

Dependencies:
  @backstage/app-defaults                                          1.5.0
  @backstage/backend-app-api                                       0.5.14, 0.6.2
  @backstage/backend-common                                        0.21.3, 0.21.6
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.6
  @backstage/backend-plugin-api                                    0.6.13, 0.6.16
  @backstage/backend-tasks                                         0.5.18, 0.5.21
  @backstage/catalog-client                                        1.6.0, 1.6.3
  @backstage/catalog-model                                         1.4.4, 1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.3, 0.2.4
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.6.2, 1.7.0
  @backstage/config                                                1.1.1, 1.2.0
  @backstage/core-app-api                                          1.12.0
  @backstage/core-compat-api                                       0.2.0
  @backstage/core-components                                       0.13.10, 0.14.0, 0.14.3
  @backstage/core-plugin-api                                       1.9.0, 1.9.1
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.3, 1.2.4
  @backstage/eslint-plugin                                         0.1.5
  @backstage/frontend-plugin-api                                   0.6.0, 0.6.3
  @backstage/integration-aws-node                                  0.1.12, 0.1.9
  @backstage/integration-react                                     1.1.24, 1.1.25
  @backstage/integration                                           1.9.0, 1.9.1
  @backstage/plugin-api-docs                                       0.11.0
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.8
  @backstage/plugin-auth-backend-module-github-provider            0.1.10
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.10
  @backstage/plugin-auth-backend-module-google-provider            0.1.10
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.8
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.10
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.6
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.3
  @backstage/plugin-auth-backend-module-okta-provider              0.0.6
  @backstage/plugin-auth-backend                                   0.21.3
  @backstage/plugin-auth-node                                      0.4.11, 0.4.8
  @backstage/plugin-catalog-backend-module-github                  0.5.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.10
  @backstage/plugin-catalog-backend                                1.17.3
  @backstage/plugin-catalog-common                                 1.0.21, 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.0
  @backstage/plugin-catalog-import                                 0.10.6
  @backstage/plugin-catalog-node                                   1.11.0, 1.7.3
  @backstage/plugin-catalog-react                                  1.10.0, 1.11.2
  @backstage/plugin-catalog                                        1.17.0
  @backstage/plugin-events-node                                    0.2.22
  @backstage/plugin-gcp-projects                                   0.3.46
  @backstage/plugin-github-actions                                 0.6.11
  @backstage/plugin-home-react                                     0.1.8
  @backstage/plugin-home                                           0.6.2
  @backstage/plugin-kubernetes-backend                             0.16.4
  @backstage/plugin-kubernetes-common                              0.7.5
  @backstage/plugin-kubernetes-node                                0.1.10
  @backstage/plugin-kubernetes-react                               0.3.3
  @backstage/plugin-kubernetes                                     0.11.8
  @backstage/plugin-org                                            0.6.20
  @backstage/plugin-permission-common                              0.7.12, 0.7.13
  @backstage/plugin-permission-node                                0.7.24, 0.7.27
  @backstage/plugin-permission-react                               0.4.20, 0.4.21
  @backstage/plugin-proxy-backend                                  0.4.11
  @backstage/plugin-scaffolder-backend-module-azure                0.1.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.3
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.3
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.3
  @backstage/plugin-scaffolder-backend-module-github               0.2.3
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.16
  @backstage/plugin-scaffolder-backend                             1.21.3
  @backstage/plugin-scaffolder-common                              1.5.0
  @backstage/plugin-scaffolder-node                                0.3.3
  @backstage/plugin-scaffolder-react                               1.8.0
  @backstage/plugin-scaffolder                                     1.18.0
  @backstage/plugin-search-backend-module-catalog                  0.1.17
  @backstage/plugin-search-backend-module-pg                       0.5.22
  @backstage/plugin-search-backend-node                            1.2.17
  @backstage/plugin-search-backend                                 1.5.3
  @backstage/plugin-search-common                                  1.2.10, 1.2.11
  @backstage/plugin-search-react                                   1.7.6
  @backstage/plugin-search                                         1.4.6
  @backstage/plugin-todo                                           0.2.34
  @backstage/plugin-user-settings                                  0.8.1
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.6.3
  @backstage/test-utils                                            1.5.0
  @backstage/theme                                                 0.4.4, 0.5.1, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
```

**Comment by cquinones100** [comment]
I think this might be related to what [my PR](https://github.com/AntoineDao/backstage-provider-kubernetes/pull/5) is addressing.
